version: '3.8'

services:
  app:
    image: denoland/deno:latest
    container_name: deno_app
    ports:
      - "8000:8000" 
    working_dir: /app
    volumes:
      - .:/app
    command: deno run -A --watch main.ts
    depends_on:
      - db
    # environment:
    #   - MONGO_URL=mongodb://db:27017/projetoAGX

  db:
    image: mongo:latest
    container_name: mongodb_agx
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
